global_frame: map
robot_base_frame: base_link
update_frequency: 5.0
publish_frequency: 2.0

#set if you want the voxel map published
publish_voxel_map: false

#set to true if you want to initialize the costmap from a static map
static_map: false

#begin - COMMENT these lines if you set static_map to true
rolling_window: true
width: 50.0
height: 50.0
resolution: 0.2
#end - COMMENT these lines if you set static_map to true

#START VOXEL STUFF
map_type: voxel
origin_z: 0.0
z_resolution: 0.2
z_voxels: 10
unknown_threshold: 10
mark_threshold: 0
#END VOXEL STUFF

transform_tolerance: 0.3
obstacle_range: 24.95
max_obstacle_height: 2.0
raytrace_range: 25
#footprint: [[-1.000, -1.000], [-1.000, 1.000], [1.000, 1.000], [1.35, 0.0], [1.000, -1.000]]
robot_radius: 1.97
footprint_padding: 0.01
#inflation_radius: 4.0 # Overwritten in launch file
track_unknown_space: true # Assume unknown cells if no data (cost=-1)
#cost_scaling_factor: 0.30809 # calculated in launch file and overwritten = 0.92425890152 / (desired_inflation_radius - robot_radius)
lethal_cost_threshold: 100
#observation_sources: base_scan
#base_scan: {data_type: LaserScan, expected_update_rate: 0.4,
#observation_persistence: 0.0, marking: true, clearing: true, max_obstacle_height: 0.4, min_obstacle_height: 0.08}
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: lidar_link, data_type: LaserScan, topic: lidar/scan, observation_persistence: 0.0, marking: true, clearing: true, max_obstacle_height: 2.0, min_obstacle_height: 0.0, inf_is_valid: true}

combination_method: 0 # overwrite earlier costmap